Ext.define('playgrounds.model.Playground', {
	extend: 'Ext.data.Model',
	config: {
		fields: [
			"name",
		    "location",
		    "access",
		    "field4",
		    "field5",
		    "xcoord",
		    "ycoord",
		    "name",
		    "location",
		    "council",
		    "council email",
		    "name",
		    "location",
		    "access",
		    "greenspace",
		    "early",
		    "mid",
		    "older",
		    "equip",
		    "gym",
		    "hanging",
		    "swings",
		    "sliding",
		    "spinning",
		    "climbing",
		    "sandpit",
		    "balance",
		    "activity",
		    "modular",
		    "quality",
		    "swing_d",
		    "access_d",
		    "modular_d",
		    "fences",
		    "shade",
		    "drink",
		    "seat",
		    "table",
		    "bbq",
		    "toilet",
		    "bins",
		    "icon_bbq",
		    "icon_cycling",
		    "icon_disabled",
		    "icon_dog",
		    "icon_fence",
		    "icon_picnic",
		    "icon_playeq",
		    "icon_shadedeq",
		    "icon_shelter",
		    "icon_sports",
		    "icon_toilets",
		    "icon_walking"
		]
	}

});